# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python 3.8: TypeError: 'type' object is not subscriptable
        python-version: [3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # gym 0.21 installation is broken with more recent versions of pip
        # see https://stackoverflow.com/questions/77124879/pip-extras-require-must-be-a-dictionary-whose-values-are-strings-or-lists-of
        # python -m pip install --upgrade pip
        pip install setuptools==65.5.0 pip==21  
        pip install wheel==0.38.0   

        pip install flake8 pytest
        # TODO: raises an error: The conflict is caused by:
        # The user requested diffscore 0.0.1 (from /home/runner/work/diffscore/diffscore)
        # similarity-repository 0.0.1 depends on diffscore 0.0.1 (from git+https://github.com/nacloos/diffscore.git)
        # pip install -e .
        # ok if consistent with diffscore dep in similarity-repository
        pip install git+https://github.com/nacloos/diffscore.git

        git clone https://github.com/nacloos/similarity-repository.git
        cd similarity-repository
        pip install -e .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
